#!/bin/sh

[ -f /etc/htcNet ] && . /etc/htcNet

LOGFILE=/var/log/htcNet-cmd.log
CMD="$1"

log() {
    NOW=$(date +"%F %H:%M:%S")
    LOG="[$NOW] $1"
    echo "$LOG"
    echo "$LOG" >> "$LOGFILE"
}

if [ -z "$APPEND_LOG" ]; then
    echo "NO APPEND LOG"
    truncate -s 0 "$LOGFILE"
fi

if [ -z "$CMD" ]; then
    log "FATAL: Empty command!"
    exit -1
fi

log "RUNNING COMMAND $CMD"

SCRIPT_URL="http://$HOST/htcNet/$CMD.sh"

log "Download: $SCRIPT_URL"

SCRIPT=$(curl -fsSL $SCRIPT_URL)

log "Downloaded. RUN"

sh -c "$SCRIPT" 2>&1 | tee -a "$LOGFILE"

log "DONE"
